version: '3.8'

services:

  flyway-migration:
    image: flyway/flyway:10
    container_name: production-flyway-runner

    entrypoint: [ "flyway", "migrate" ]

    volumes:
      - ./sql_versions:/flyway/sql:ro

    environment:
      - FLYWAY_URL=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
      - FLYWAY_USER=${DB_USER}
      - FLYWAY_PASSWORD=${DB_PASSWORD}
      - FLYWAY_SCHEMAS=health

  fastapi:
    image: ${ECR_REPOSITORY_URL}:${IMAGE_TAG}

    container_name: production-fastapi-app

    ports:
      - "8000:8000"

    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}
      - REDIS_URL=redis://${REDIS_HOST}:6379/0

      - PAYFAST_MERCHANT_ID=${PAYFAST_MERCHANT_ID}
      - PAYFAST_MERCHANT_KEY=${PAYFAST_MERCHANT_KEY}
      - PAYFAST_PASSPHRASE=${PAYFAST_PASSPHRASE}
      - PAYFAST_SANDBOX=${PAYFAST_SANDBOX}

      - AGORA_APP_ID=${AGORA_APP_ID}
      - AGORA_APP_CERTIFICATE=${AGORA_APP_CERTIFICATE}
      - FRONTEND_BASE_URL =${FRONTEND_BASE_URL}
      - APP_BASE_URL =${APP_BASE_URL}

    depends_on:
      flyway-migration:
        condition: service_completed_successfully

